### ISSUE TITLE
How to use this action on github enterprise?

### ISSUE THREAD

**Issue by Kamilcuk** [actions-rust-lang/setup-rust-toolchain#37]
Our github enterprise has no access to github.com. This action `action.yml` includes the following action:

    uses: Swatinem/rust-cache@v2

However, even with `cache: false`:

```
      - uses: ourenterprise/thirdparty.setup-rust-toolchain@v1
        with:
          components: rustfmt
          cache: false
      - uses: avt/thirdparty.rust-cache@v2
```

The runner still tries to download the action:

```
Download action repository 'ourenterprise/thirdparty.setup-rust-toolchain@v1' (SHA:b113a[30](https://ourenterprise.com/ourenterprise/ourenterprise?check_suite_focus=true#step:1:31)d27a8e59c969077c0a0168cc13dab5ffc)
Download action repository 'ourenterprise/thirdparty.rust-cache@v2' (SHA:23bce251a8cd2ffc3c1075eaa2367cf899916d84)
Getting action download info
Error: Unable to resolve action `Swatinem/rust-cache@v2`, repository not found on this server. If you want to use this action from GitHub.com, see the following documentation: https://docs.github.com/en/enterprise/admin/github-actions/managing-access-to-actions-from-githubcom
```

Is it possible so that runner will not resolve all actions?

Would it be possible to add another `uses:` parameter to this action to specify the location of `rust-cache` as `ourenterprise/thirdparty.rust-cache@v2`?

Thanks.

**Comment by jonasbb** [comment]
Sorry to hear that the action does not work for you. I cannot support your scenario, since I have no way to test it, but I can accept a PR to make it more suitable for you.

> Is it possible so that runner will not resolve all actions?

That is something you have to settle with GitHub or your system administrator. It feels like a runner wouldn't need to download code if it will not execute it.

> Would it be possible to add another `uses:` parameter to this action to specify the location of `rust-cache` as `ourenterprise/thirdparty.rust-cache@v2`?

I don't see a way to make anything of the `uses:` part dynamic. There seem to be no contexts (`input` or `env`) to load a dynamic value. https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability
You seem to mirror this action. Probably as part of this step you should adjust the action URLs.
