### ISSUE TITLE
Ability to install without setting override

### ISSUE THREAD

**Issue by jayvdb** [actions-rust-lang/setup-rust-toolchain#38]
This action has one significant difference to https://github.com/actions-rs/toolchain in that it defaults to overriding the toolchain, whereas the old action only does that if `override: true` is set.

It would be nice to be able to opt out of that override.

**Comment by jonasbb** [comment]
The override is necessary as otherwise it is not possible to use a different toolchain than specified in the `rust-toolchain.toml` see #26 and #31. Can you please explain what your use case is and why the current way is a problem for you?

The override isn't anything special, so you can get rid of it by executing `rustup override unset` after this action. I hope that helps.

**Comment by jayvdb** [comment]
We install nightly only for its rustfmt , and dont want to build with it.

Yes, I am using `rustup override` after this github action in order to clear it.  I would prefer not having the extra step, by telling this action that I do not want it.

**Comment by jonasbb** [comment]
I added this as an option in 4d1965c9142484e48d40c19de54b5cba84953a06.
