### ISSUE TITLE
Using `setup-rust-toolchain` multiple times in the same job issues a warning on macOS

### ISSUE THREAD

**Issue by clechasseur** [actions-rust-lang/setup-rust-toolchain#42]
If I include multiple uses of `actions-rust-lang/setup-rust-toolchain` in the same workflow job (to install two different Rust versions), when run on macOS, a warning about `bash` already being installed is issued:

```
bash 5.2.26 is already installed and up-to-date. To reinstall 5.2.26, run: brew reinstall bash
```

Sample run: https://github.com/clechasseur/msrv-prep/actions/runs/10154329214

Screenshot, in case the run expires:
![image](https://github.com/user-attachments/assets/4c202d85-393f-4282-a86d-aaa4614ff30f)

**Comment by jonasbb** [comment]
The action is not meant to be executed multiple times in a single job, since modifying the environment, setting up the cache and error highlighters are global changes. As such there might be more stuff that doesn't quite work right if you do that. I added the possibility to install multiple Rust toolchains at once with b31b1317f290cc8743fce262ee98435b8c2a3c5a. This hopefully eliminates the need to execute the action multiple times.

As for brew specifically, I do not use Mac, so I am not familiar with brew, but I couldn't find any command line options that would avoid the warning. However, if you have an idea PRs are welcome.

**Comment by clechasseur** [comment]
Actually, I didn't know you could now install multiple versions with one invocation. That completely solves my problem. Thank you!
