### ISSUE TITLE
Please add rust profile for the action

### ISSUE THREAD

**Issue by mikolajsobolewski** [actions-rust-lang/setup-rust-toolchain#46]
For example usage:
```
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          profile: production
```

**Comment by jonasbb** [comment]
Please expand what you want to achieve here and how you want to achieve it. It sounds like you are talking about [cargo custom profiles](https://doc.rust-lang.org/cargo/reference/profiles.html#custom-profiles) and not about rustup profiles. `setup-rust-toolchain` really is more concerned with rustup and setting up a nice environment to use `cargo` in later on.

Cargo profiles are not really global. You don't want to set a custom profile globally, as that would break `cargo install`. There are good reasons to use different profiles for test, doc, release. That is why multiple are pre-defined.

**Comment by amaanq** [comment]
I don't mean to hijack, but since the author didn't clarify if they meant cargo profiles or not, what about [Rustup profiles](https://rust-lang.github.io/rustup/concepts/profiles.html)? I'd like to use the minimal profile with this action, if possible. Maybe I missed the docs but I couldn't see any mention of that anywhere

**Comment by jonasbb** [comment]
> I don't mean to hijack, but since the author didn't clarify if they meant cargo profiles or not, what about [Rustup profiles](https://rust-lang.github.io/rustup/concepts/profiles.html)? I'd like to use the minimal profile with this action, if possible. Maybe I missed the docs but I couldn't see any mention of that anywhere

The action uses the `minimal` profile. This avoids installing unused components and forces you to be explicit about what you depend on, for the CI pipeline. As such, I don't think switching to `default` is a good choice. As for `complete`, the linked page even discourages the usage.
I feel like @mikolajsobolewski asked about cargo profiles, since there is no `production` rustup profile.

**Comment by amaanq** [comment]
Oh great, that's awesome. Thank you!

**Comment by jonasbb** [comment]
Since there was no response about the `production` profile, I am going to close the issue.
